### ISSUE TITLE
Not working on v7

### ISSUE THREAD

**Issue by raffel080108** [L0615T1C5-216AC-9437/MaxRateCalculator#6]
The mod does not appear to be working on the latest version of the game and shows as incompatible

**Comment by L0615T1C5-216AC-9437** [comment]
@raffel080108 The mod has been abandoned due to a lack of motivation on my part. If you really want to use the mod you could try updating the source code to the latest version and see if it compiles.

**Comment by raffel080108** [comment]
Ok. If the mod doesn't work on v7 then I wouldn't mark it with the v7 tag, causes confusion I would say (like in this case)
